id: A14419104
base_file: f50D4.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:05:04.121755
  last_modified_at: 2022-06-17 14:05:04.121796
