id: A14419104
base_file: f2AEA.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:05:04.117198
  last_modified_at: 2022-06-17 14:05:04.117219
